Avoid incompatible types in java 11 for Stream::mapToInt
Error:(62, 35) java: incompatible types: invalid method reference
    method intValue in class java.lang.Integer cannot be applied to given types
      required: no arguments
      found: java.lang.Object
      reason: actual and formal argument lists differ in length